//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrupowy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektGrupowy.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybut jest wymagany..
        /// </summary>
        public static string AttributeIsRequired {
            get {
                return ResourceManager.GetString("AttributeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono atrybutu..
        /// </summary>
        public static string AttributeNotFound {
            get {
                return ResourceManager.GetString("AttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość atrybutu i jego typ są niezgodne..
        /// </summary>
        public static string AttributeTypeError {
            get {
                return ResourceManager.GetString("AttributeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono definicji elementu..
        /// </summary>
        public static string ElementDefinitionNotFound {
            get {
                return ResourceManager.GetString("ElementDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono elementu.
        /// </summary>
        public static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany login już istnieje..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login jest wymagany..
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator gry jest wymagany..
        /// </summary>
        public static string GameIdIsRequired {
            get {
                return ResourceManager.GetString("GameIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra o podanym identyfikatorze nie istnieje..
        /// </summary>
        public static string GameNotExists {
            get {
                return ResourceManager.GetString("GameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra nie istnieje lub nie masz do niej dostępu..
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny identyfikator..
        /// </summary>
        public static string InvalidGameId {
            get {
                return ResourceManager.GetString("InvalidGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login lub hasło jest błędne..
        /// </summary>
        public static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne hasło..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa jest wymagana.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick jest wymagany..
        /// </summary>
        public static string NickIsRequired {
            get {
                return ResourceManager.GetString("NickIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest wymagane..
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło mus zawierać co najmniej 3 znaki..
        /// </summary>
        public static string PasswordShorterThan3 {
            get {
                return ResourceManager.GetString("PasswordShorterThan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie pasują..
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono defenicji żetonu..
        /// </summary>
        public static string TokenDefinitionNotFound {
            get {
                return ResourceManager.GetString("TokenDefinitionNotFound", resourceCulture);
            }
        }
    }
}
