//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrupowy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektGrupowy.Resources.Rules", typeof(Rules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project planning&amp;Priority valuation&amp;Project structural analysis&amp;Operation planning.
        /// </summary>
        public static string AvaxStorming_Applications {
            get {
                return ResourceManager.GetString("AvaxStorming_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avax Storming game is designated to estimate project structure and it&apos;s priorities.
        /// </summary>
        public static string AvaxStorming_Description {
            get {
                return ResourceManager.GetString("AvaxStorming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents one of product&apos;s functionalities&amp;Represents project module or project stage.
        /// </summary>
        public static string AvaxStorming_Elements {
            get {
                return ResourceManager.GetString("AvaxStorming_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvaxStorming_Tokens {
            get {
                return ResourceManager.GetString("AvaxStorming_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring project requirements&amp;Priorities valuation&amp;Analysis of the demand for a given functionality.
        /// </summary>
        public static string BuyaFeature_Applications {
            get {
                return ResourceManager.GetString("BuyaFeature_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy A Feature game is designated to estimate range and specify priorities of project&apos;s features.
        /// </summary>
        public static string BuyaFeature_Description {
            get {
                return ResourceManager.GetString("BuyaFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents project&apos;s functionality.
        /// </summary>
        public static string BuyaFeature_Elements {
            get {
                return ResourceManager.GetString("BuyaFeature_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents money that can be spent on project functionalities.
        /// </summary>
        public static string BuyaFeature_Tokens {
            get {
                return ResourceManager.GetString("BuyaFeature_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usystematyzowanie procesu wytwarzania&amp;Określanie poziomu trudności zadań&amp;Planowanie projektu&amp;Szacowanie priorytetów&amp;Planowanie procesu.
        /// </summary>
        public static string HowNowWowMatrix_Applications {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole gry podzielone jest na 3 kwadraty symbolizujące następujące grupy: - HOW - trudne zadanie - niemożliwe do implementacji i wysokim stopni oryginalności, -WOW - łatwe zadania o wysokiej oryginalności - NOW- łatwe i mało oryginalne zadania. Gracze wypisują na kartkach swoje pomysły a następnie w formie głosowania przydzielają je do jedenj z grup..
        /// </summary>
        public static string HowNowWowMatrix_Description {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje pomysł/ideę, którą można wdrożyć/zaimplementować.
        /// </summary>
        public static string HowNowWowMatrix_Elements {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowNowWowMatrix_Tokens {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration/process rating&amp;Risk analysis&amp;Evaluation of project&apos;s pros and cons&amp;Searching results&amp;Sprint Retrospective.
        /// </summary>
        public static string SpeedBoat_Applications {
            get {
                return ResourceManager.GetString("SpeedBoat_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Boat game is designated to identifying project&apos;s chances and threats. Project is presented as a boat, threats as anchors and chances as propellers.
        /// </summary>
        public static string SpeedBoat_Description {
            get {
                return ResourceManager.GetString("SpeedBoat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents threat, flaw, something that slows down the project.&amp;Represents chance, advantage, something that speeds up the project..
        /// </summary>
        public static string SpeedBoat_Elements {
            get {
                return ResourceManager.GetString("SpeedBoat_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpeedBoat_Tokens {
            get {
                return ResourceManager.GetString("SpeedBoat_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing and analyzing information&amp;Strategy building&amp;Decision-making&amp;Viability study.
        /// </summary>
        public static string SWOTAnalysis_Applications {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWOT Analysis  is an acronym for strengths, weaknesses, opportunities, and threats and is a structured planning method that evaluates those four elements of an organization, project or business venture..
        /// </summary>
        public static string SWOTAnalysis_Description {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents project&apos;s strengths.&amp;Represents project&apos;s weaknesses.&amp;Represents project&apos;s chances.&amp;Represents project&apos;s threats..
        /// </summary>
        public static string SWOTAnalysis_Elements {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SWOTAnalysis_Tokens {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikacja wyróżników produktu&amp;Określenie kierunku rozwoju produktu.
        /// </summary>
        public static string WholeProduct_Applications {
            get {
                return ResourceManager.GetString("WholeProduct_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra Whole Produkt wspomaga proces identyfikacji tych cech produktu, które powodują, że staje się on bardziej atrakcyjny i wyróżnia się na tle konkurencji. Podejście to pozwala również określić kierunek dalszego rozwoju produktu, tak aby przyciągnąć nowych klientów..
        /// </summary>
        public static string WholeProduct_Description {
            get {
                return ResourceManager.GetString("WholeProduct_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje cechę produktu..
        /// </summary>
        public static string WholeProduct_Elements {
            get {
                return ResourceManager.GetString("WholeProduct_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WholeProduct_Tokens {
            get {
                return ResourceManager.GetString("WholeProduct_Tokens", resourceCulture);
            }
        }
    }
}
