//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrupowy.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektGrupowy.Resources.Rules", typeof(Rules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Planowanie projektu&amp;Szacowanie priorytetów&amp;Analiza strukturalna projektu&amp;Planowanie procesu.
        /// </summary>
        public static string AvaxStorming_Applications {
            get {
                return ResourceManager.GetString("AvaxStorming_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gra Avax Storming przeznaczona jest do oszacowania struktury i priorytetów w projekcie..
        /// </summary>
        public static string AvaxStorming_Description {
            get {
                return ResourceManager.GetString("AvaxStorming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje jakąś funkcjonalność produktu/projektu.&amp;Reprezentuje moduł projektu lub etap w projekcie..
        /// </summary>
        public static string AvaxStorming_Elements {
            get {
                return ResourceManager.GetString("AvaxStorming_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string AvaxStorming_Tokens {
            get {
                return ResourceManager.GetString("AvaxStorming_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozyskiwanie wymagań&amp;Szacowanie priorytetów&amp;Analiza zapotrzebowania na daną funkcjonalność.
        /// </summary>
        public static string BuyaFeature_Applications {
            get {
                return ResourceManager.GetString("BuyaFeature_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gra Buy a Feature przeznaczona jest do szacowania zakresu i określenia priorytetów elementów funkcjonalnych projektu..
        /// </summary>
        public static string BuyaFeature_Description {
            get {
                return ResourceManager.GetString("BuyaFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje jakąś funkcjonalność produktu/projektu..
        /// </summary>
        public static string BuyaFeature_Elements {
            get {
                return ResourceManager.GetString("BuyaFeature_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje pieniądze jakie można postawić na daną funkcjonalność..
        /// </summary>
        public static string BuyaFeature_Tokens {
            get {
                return ResourceManager.GetString("BuyaFeature_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Planowanie projektu&amp;Szacowanie priorytetów&amp;Analiza strukturalna projektu&amp;Planowanie procesu.
        /// </summary>
        public static string HowNowWowMatrix_Applications {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DupaDupaDupa.
        /// </summary>
        public static string HowNowWowMatrix_Description {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ReprezentujeDupe.
        /// </summary>
        public static string HowNowWowMatrix_Elements {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string HowNowWowMatrix_Tokens {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ocena iteracji/procesu&amp;Analiza ryzyka&amp;Ocena wad i zalet produktu&amp;Retrospektywa sprintu.
        /// </summary>
        public static string SpeedBoat_Applications {
            get {
                return ResourceManager.GetString("SpeedBoat_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gra Speed Boat przeznaczona jest do identyfikacji zagrożeń i szans projektu. Projekt przedstawiony jest jako łódź, zagrożenia jako kotwice, zaś szanse jako turbiny/śmigła..
        /// </summary>
        public static string SpeedBoat_Description {
            get {
                return ResourceManager.GetString("SpeedBoat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje zagrożenie, wadę, obiekt opóźniający projekt.&amp;Reprezentuje szansę, zaletę, obiekt przyśpieszający projekt..
        /// </summary>
        public static string SpeedBoat_Elements {
            get {
                return ResourceManager.GetString("SpeedBoat_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string SpeedBoat_Tokens {
            get {
                return ResourceManager.GetString("SpeedBoat_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Porządkowanie i analiza informacji.
        /// </summary>
        public static string SWOTAnalysis_Applications {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SWOT – popularna heurystyczna technika służąca do porządkowania i analizy informacji..
        /// </summary>
        public static string SWOTAnalysis_Description {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje silną stronę projektu.&amp;Reprezentuje słabą stronę projektu.&amp;Reprezentuje szansę.&amp;Reprezentuje zagrożenie..
        /// </summary>
        public static string SWOTAnalysis_Elements {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string SWOTAnalysis_Tokens {
            get {
                return ResourceManager.GetString("SWOTAnalysis_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identyfikacja wyróżników produktu&amp;Określenie kierunku rozwoju produktu.
        /// </summary>
        public static string WholeProduct_Applications {
            get {
                return ResourceManager.GetString("WholeProduct_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gra Whole Produkt wspomaga proces identyfikacji tych cech produktu, które powodują, że staje się on bardziej atrakcyjny i wyróżnia się na tle konkurencji. Podejście to pozwala również określić kierunek dalszego rozwoju produktu, tak aby przyciągnąć nowych klientów..
        /// </summary>
        public static string WholeProduct_Description {
            get {
                return ResourceManager.GetString("WholeProduct_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reprezentuje cechę produktu..
        /// </summary>
        public static string WholeProduct_Elements {
            get {
                return ResourceManager.GetString("WholeProduct_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string WholeProduct_Tokens {
            get {
                return ResourceManager.GetString("WholeProduct_Tokens", resourceCulture);
            }
        }
    }
}
