//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrupowy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektGrupowy.Resources.Rules", typeof(Rules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planowanie projektu&amp;Szacowanie priorytetów&amp;Analiza strukturalna projektu&amp;Planowanie procesu.
        /// </summary>
        public static string AvaxStorming_Applications {
            get {
                return ResourceManager.GetString("AvaxStorming_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra Avax Storming przeznaczona jest do oszacowania struktury i priorytetów w projekcie..
        /// </summary>
        public static string AvaxStorming_Description {
            get {
                return ResourceManager.GetString("AvaxStorming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje jakąś funkcjonalność produktu/projektu.&amp;Reprezentuje moduł projektu lub etap w projekcie..
        /// </summary>
        public static string AvaxStorming_Elements {
            get {
                return ResourceManager.GetString("AvaxStorming_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AvaxStorming_Tokens {
            get {
                return ResourceManager.GetString("AvaxStorming_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozyskiwanie wymagań&amp;Szacowanie priorytetów&amp;Analiza zapotrzebowania na daną funkcjonalność.
        /// </summary>
        public static string BuyaFeature_Applications {
            get {
                return ResourceManager.GetString("BuyaFeature_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra Buy a Feature przeznaczona jest do szacowania zakresu i określenia priorytetów elementów funkcjonalnych projektu..
        /// </summary>
        public static string BuyaFeature_Description {
            get {
                return ResourceManager.GetString("BuyaFeature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje jakąś funkcjonalność produktu/projektu..
        /// </summary>
        public static string BuyaFeature_Elements {
            get {
                return ResourceManager.GetString("BuyaFeature_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje pieniądze jakie można postawić na daną funkcjonalność..
        /// </summary>
        public static string BuyaFeature_Tokens {
            get {
                return ResourceManager.GetString("BuyaFeature_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planowanie projektu&amp;Szacowanie priorytetów&amp;Analiza strukturalna projektu&amp;Planowanie procesu.
        /// </summary>
        public static string HowNowWowMatrix_Applications {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DupaDupaDupa.
        /// </summary>
        public static string HowNowWowMatrix_Description {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReprezentujeDupe.
        /// </summary>
        public static string HowNowWowMatrix_Elements {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HowNowWowMatrix_Tokens {
            get {
                return ResourceManager.GetString("HowNowWowMatrix_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena iteracji/procesu&amp;Analiza ryzyka&amp;Ocena wad i zalet produktu&amp;Retrospektywa sprintu.
        /// </summary>
        public static string SpeedBoat_Applications {
            get {
                return ResourceManager.GetString("SpeedBoat_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra Speed Boat przeznaczona jest do identyfikacji zagrożeń i szans projektu. Projekt przedstawiony jest jako łódź, zagrożenia jako kotwice, zaś szanse jako turbiny/śmigła..
        /// </summary>
        public static string SpeedBoat_Description {
            get {
                return ResourceManager.GetString("SpeedBoat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje zagrożenie, wadę, obiekt opóźniający projekt.&amp;Reprezentuje szansę, zaletę, obiekt przyśpieszający projekt..
        /// </summary>
        public static string SpeedBoat_Elements {
            get {
                return ResourceManager.GetString("SpeedBoat_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SpeedBoat_Tokens {
            get {
                return ResourceManager.GetString("SpeedBoat_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikacja wyróżników produktu&amp;Określenie kierunku rozwoju produktu.
        /// </summary>
        public static string WholeProduct_Applications {
            get {
                return ResourceManager.GetString("WholeProduct_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gra Whole Produkt wspomaga proces identyfikacji tych cech produktu, które powodują, że staje się on bardziej atrakcyjny i wyróżnia się na tle konkurencji. Podejście to pozwala również określić kierunek dalszego rozwoju produktu, tak aby przyciągnąć nowych klientów..
        /// </summary>
        public static string WholeProduct_Description {
            get {
                return ResourceManager.GetString("WholeProduct_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentuje cechę produktu..
        /// </summary>
        public static string WholeProduct_Elements {
            get {
                return ResourceManager.GetString("WholeProduct_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WholeProduct_Tokens {
            get {
                return ResourceManager.GetString("WholeProduct_Tokens", resourceCulture);
            }
        }
    }
}
